name: Deploy Loudrr

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_run:
    workflows: ["Build Loudrr"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PASS: ${{ secrets.SSH_PASS }}
      USER: ${{ secrets.SSH_PASS }}
      SERVER: ${{ secrets.STAGING_SERVER }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get -y install sshpass
          sudo apt-get -y install zip unzip
       
      - name:  Download the Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: build-output
          path: ./app/build.zip
          if-no-files-found: error
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: app
