# This is a basic workflow to help you get started with Actions

name: Build Loudrr

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    paths:
      - "app/**"
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PASS: ${{ secrets.SSH_PASS }}
      USER: ${{ secrets.SSH_USER }}
      SERVER: ${{ secrets.STAGING_SERVER }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      NEXT_PUBLIC_BRAND_NAME: ${{ secrets.NEXT_PUBLIC_BRAND_NAME }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.STAGING_PORT }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Yarn
        run: npm install -g yarn
      
      - name: Install sshpass
        run: |
          sudo apt-get -y install sshpass zip unzip rsync
          
      - name: Create env file
        uses: javajawa/create-envfile@v1
        with:
          file_name: app/.env.production
          envkey_PORT: ${{ secrets.STAGING_PORT }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_NEXT_PUBLIC_BRAND_NAME: ${{ secrets.NEXT_PUBLIC_BRAND_NAME }}
          envkey_HOST: ${{ secrets.HOST }}
          envkey_GITHUB_CLIENT_ID: ${{ secrets.GIT_CLIENT_ID }}
          envkey_GITHUB_CLIENT_SECRET: ${{ secrets.GIT_CLIENT_SECRET }}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          envkey_FB_CLIENT_ID: ${{ secrets.FB_CLIENT_ID }}
          envkey_FB_CLIENT_SECRET: ${{ secrets.FB_CLIENT_SECRET }}
       
      # Runs a set of commands using the runners shell
      - name: build the artifact.
        run: |
          ls -la
          echo "==============="
          cat app/.env.production
          cd app
          echo "==============="
          ls -la
          yarn && yarn build
          
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/app/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
                 
      - name: Deploy artifact
        run: |
          echo "sshpass -p ${PASS} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER@$SERVER -p $PORT \"cd experiments/loudrr-staging && rm -rf ./**\""
          sshpass -p ${PASS} rsync --progress -avz -e "ssh -p ${PORT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" . $USER@$SERVER:experiments/loudrr-staging/
          sshpass -p ${PASS} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER@$SERVER -p $PORT "cd experiments/loudrr-staging/app; pm2  restart loudrr-staging;"
          
 
